development:
  adapter: postgresql
  encoding: unicode
  database: epicstories_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: epicstories_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: epicstories_production
  pool: 5
